FoodOnline/FoodOnline/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FoodOnline/accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("registerUser/", views.registerUser, name="registerUser"),
    path("registerVendor/", views.registerVendor, name="registerVendor"),
    path("login/", views.login, name="login"),
    # path("logout/", views.logout, name="logout"),
    # path("dashboard/", views.dashboard, name="dashboard"),
]

FoodOnline/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver


class UserManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError("user must have an email address")

        if not username:
            raise ValueError("user must have an username")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password=None):
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=password,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):

    RESTAURANT = 1
    CUSTOMER = 2

    ROLE_CHOICE = ((RESTAURANT, "restaurant"), (CUSTOMER, "customer"))

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=12, blank=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICE, blank=True, null=True)

    # required fields
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    objects = UserManager()  # Link the custom user manager

    def __str__(self):
        return self.first_name

    USERNAME_FIELD = "email"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    profile_picture = models.ImageField(
        upload_to="users/profile_picture", blank=True, null=True
    )
    cover_photo = models.ImageField(
        upload_to="users/cover_picture", blank=True, null=True
    )
    address_line_1 = models.CharField(max_length=100, blank=True, null=True)
    address_line_2 = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=30, blank=True, null=True)
    state = models.CharField(max_length=30, blank=True, null=True)
    city = models.CharField(max_length=30, blank=True, null=True)
    pin_code = models.CharField(max_length=10, blank=True, null=True)
    latitude = models.CharField(max_length=10, blank=True, null=True)
    longitude = models.CharField(max_length=10, blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.user.email


# #way1
# # Receiver function
# def post_user_create_profile_receiver(sender, instance, created, **kwargs):
#     pass


# post_save.connect(post_user_create_profile_receiver, sender=User)

# way2


@receiver(post_save, sender=User)
def post_user_create_profile_receiver(sender, instance, created, **kwargs):
    # print(created)  # True
    if created:
        UserProfile.objects.create(user=instance)
        # print("user profile created ")
    else:
        try:
            profile = UserProfile.objects.get(user=instance)
            profile.save()
        except:
            UserProfile.objects.create(user=instance)
            # print("Profile does not exist , but we created one!!")
        print("user is updated")


@receiver(pre_save, sender=User)
def pre_save_profile_receiver(sender, instance, **kwargs):
    pass
    # print(instance.first_name, "this user is being saved")

FoodOnline/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FoodOnline</title>
    <!-- Google Font Family Link Start -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
    <!-- Google Font Family Link End -->

    <!-- CSS -->
    <link href="{% static 'css/iconmoon.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="{% static 'css/bootstrap-slider.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- JAVASCRIPT -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'js/modernizr.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    {% if '/' == request.path or 'profile' in request.path %}
    <script
        src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete"
        defer></script>
    {% endif %}
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="{% static 'js/custom.js' %}"></script>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id={{ PAYPAL_CLIENT_ID }}&currency=USD"></script>

    <!-- Include Datatables plugin script and css -->
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myOrdersTable').DataTable();
        });
    </script>

    <style>
        body,
        .main-section p,
        .mce-content-body p {
            font: Normal 14px/24px "Open Sans", sans-serif;
            letter-spacing: 0px;
            text-transform: none;
            color: #515151 !important;
        }
    </style>
</head>

<body>

    <!-- LOAD NAVBAR HERE -->
    {% include 'includes/navbar.html' %}

    <!-- LOAD CONTENT HERE -->
    {% block content %}
    <!-- CONTENT GOES HERE -->
    {% endblock %}

    <!-- LOAD FOOTER HERE -->
    {% include 'includes/footer.html' %}


</body>

</html>

FoodOnline/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Main Section Start -->
<div class="main-section">
    <!-- Home Pages Elements Strat -->
    <!-- Main Search Start -->
    <div class="page-section nopadding cs-nomargin main-search-bar"
        style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url({% static 'extra-images/bg-image1.jpg' %});">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="element-title">
                        <h1
                            style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
                            We are in the business of food<br>our restaurants do</h1>
                        <p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
                            Ridiculus sociosqu
                            cursus neque cursus curae ante scelerisque vehicula.</p>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                    <div class="main-search fancy bg-holder">
                        <form action="" method="GET">
                            <div class="row">
                                <div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
                                    <div class="field-holder">
                                        <input type="text" name="keyword" placeholder="Resturant name or food name">
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
                                    <div class="field-holder">
                                        <ul>
                                            <li class="select-location">
                                                <div class="foodbakery-locations-fields-group foodbakery-focus-out">
                                                    <span class="foodbakery-search-location-icon"><i
                                                            class="icon-location"></i></span>

                                                    <input type="text" name="address" class="location-field-text filter"
                                                        id="id_address" required placeholder="All Locations">
                                                    <input type="hidden" name="lat" value="" id="id_latitude">
                                                    <input type="hidden" name="lng" value="" id="id_longitude">
                                                </div>

                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <select name="radius" id="radius" style="height: 50px;" required>
                                        <option value="" selected>Choose Radius</option>
                                        <option value="5">5km</option>
                                        <option value="10">10km</option>
                                        <option value="15">15km</option>
                                        <option value="25">25km</option>
                                        <option value="50">50km</option>
                                        <option value="75">75km</option>
                                        <option value="100">100km</option>
                                    </select>
                                </div>
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                    <div class="field-holder">
                                        <input type="submit" value="Search">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Main Search End -->

    <!-- Top Restarurants Section Start -->
    <div class="page-section nopadding cs-nomargin"
        style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="element-title align-left">
                        <h2>Top Restaurants</h2>
                        <p>Explore restaurants, bars, and cafés by locality</p>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"
                    style="padding-right: 0 !important; padding-left: 0 !important;">
                    <div class="company-logo">
                        <ul>
                            {% for vendor in vendors %}
                            <li class="has-border">
                                <figure>
                                    {% if vendor.user_profile.profile_picture %}
                                    <a href=""><img src="" height="125" class="attachment-full size-full wp-post-image"
                                            alt=""></a>
                                    {% else %}
                                    <a href=""><img src="{% static 'images/default-profile.png' %}" height="125"
                                            class="attachment-full size-full wp-post-image" alt=""></a>
                                    {% endif %}
                                </figure>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Top Restarurants Section End -->
    <!-- Choose From Most Popular Listin Start -->
    <div class="page-section nopadding cs-nomargin"
        style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="element-title align-center">
                        <h2>Choose From Most Popular Restaurants</h2>
                        <p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="listing fancy">
                        <ul class="row">

                            <li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="list-post featured">
                                    <div class="img-holder">
                                        <figure>
                                            <a href="">

                                                <img src="" class="img-thumb wp-post-image" alt="">

                                                <img src="{% static 'images/default-profile.png' %}"
                                                    class="img-thumb wp-post-image" alt="">

                                            </a>
                                        </figure>

                                        <span class="restaurant-status open">
                                            <em class="bookmarkRibbon"></em>Open
                                        </span>

                                        <span class="restaurant-status close">
                                            <em class="bookmarkRibbon"></em>Close
                                        </span>


                                    </div>
                                    <div class="text-holder">

                                        <div class="post-title">
                                            <h5>
                                                <a href=""></a>
                                            </h5>
                                        </div>

                                        <span></span>

                                        <br>
                                        <span><small><b></b>away</small></span>

                                    </div>
                                    <div class="list-option">
                                        <a href="javascript:void(0);" class="shortlist-btn" data-toggle="modal"
                                            data-target="#sign-in">
                                            <i class="icon-heart-o"></i>
                                        </a>
                                    </div>
                                </div>
                            </li>







                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Choose From Most Popular Listing End -->

    <!-- Home Pages Elements End  -->
</div>
<!-- Main Section End -->
{% endblock %}

FoodOnline/templates/login.html
<!-- {% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="main-section">

    
    <h2>Text input fields</h2>

    <form>
        <label for="fname">First name:</label><br>
        <input type="text" id="fname" name="fname" value="John"><br>
        <label for="lname">Last name:</label><br>
        <input type="text" id="lname" name="lname" value="Doe">
    </form>

    <p>Note that the form itself is not visible.</p>

    <p>Also note that the default width of text input fields is 20 characters.</p>


</div>
{% endblock %} -->